//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int iduserpor { get; set; }
        public string UserId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<bool> isregister { get; set; }
        public Nullable<int> phonenum { get; set; }
        public Nullable<bool> Intrested { get; set; }
        public Nullable<int> PostId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual PostFeed PostFeed { get; set; }
    }
}
