//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int id { get; set; }
        public string VideoName { get; set; }
        public string videoSrc { get; set; }
        public Nullable<int> IdVideoCategory { get; set; }
    
        public virtual VideoCategory VideoCategory { get; set; }
    }
}
